### PR TITLE
add mtcnn-1684-mlir

### PR DESCRIPTION
**Pull request by grybd**
1) performance in stat.csv:
name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
mtcnn_rnet_bm1684_f32,1x3x24x24,3.000e-03,0.142,N/A,2.00%,N/A
mtcnn_rnet_bm1684_int8_sym,1x3x24x24,3.000e-03,0.155,N/A,1.00%,N/A
compilation,1x3x24x24,3.000e-03,0.163,N/A,3.00%,N/A
compilation,1x3x24x24,3.000e-03,0.140,N/A,3.00%,N/A
mtcnn_onet_bm1684_f32,1x3x48x48,2.000e-02,0.294,N/A,12.00%,N/A
mtcnn_onet_bm1684_int8_sym,1x3x48x48,2.000e-02,0.295,N/A,12.00%,N/A
compilation,1x3x48x48,2.000e-02,0.295,N/A,12.00%,N/A
compilation,1x3x48x48,2.000e-02,0.295,N/A,12.00%,N/A
mtcnn_pnet_bm1684_f32,1x3x12x12,9.500e-05,0.101,N/A,2.00%,N/A
mtcnn_pnet_bm1684_int8_sym,1x3x12x12,9.500e-05,0.163,N/A,3.00%,N/A
compilation,1x3x12x12,9.500e-05,0.119,N/A,4.00%,N/A
compilation,1x3x12x12,9.500e-05,0.145,N/A,2.00%,N/A
pnet-bm1684:
fp32 :flops: 92888, runtime: 0.006324ms, ComputationAbility: 0.014689T
int8:  flops: 92888, runtime: 0.005953ms, ComputationAbility: 0.015604T
rnet-bm1684:
fp32: flops: 3135244, runtime: 0.028425ms, ComputationAbility: 0.110297T
int8: flops: 3135244, runtime: 0.019169ms, ComputationAbility: 0.163557T
onet-bm1684:
fp32: flops: 26236858, runtime: 0.091931ms, ComputationAbility: 0.285398T
int8: flops: 26236858, runtime: 0.051029ms, ComputationAbility: 0.514155T

2) 驱动版本号及工具链版本信息
2.1) libsophon:0.4.5
2.2) tpu-mlir 
branch:master
commit id: 99bc396ccfd98178e92ba6917ec3cebb4db9417e

### CODE REVIEW

**Comment by grybd** [comment]
麻烦发哥帮忙触发下check @Jeffwhen

**Comment by grybd** [comment]
097d6267e1816b8efe727b73c5dbc83

**Comment by grybd** [comment]
f7d5a4e706c37e66db6e761e6a38dde
在172.28.9.198 跑过测试，没问题

**Comment by Jeffwhen** [comment]
参考 [MobileNet-Caffe-v2/mlir.config.yaml](https://github.com/sophgo/model-zoo/blob/main/vision/classification/MobileNet-Caffe-v2/mlir.config.yaml) 改一下。

**Comment by QinyuZHAO0** [comment]
已手动cherry-pick合入

**Pull request closed without merging**
