### PR TITLE
support shufflenet mode

### PR DESCRIPTION
**Pull request by alanguo1234**
support shufflenet onnx model

### CODE REVIEW

**Comment by Jeffwhen** [comment]
麻烦补充一个 README 吧

**Comment by Jeffwhen** [comment]
参考[这个](https://github.com/sophgo/model-zoo/blob/main/vision/classification/mobilenet-v2/README.md)

**Comment by Jeffwhen** [comment]
可以参考[这个](https://github.com/sophgo/model-zoo#how-to-contribute)本地先通过下。

**Comment by luluman** [comment]
#29 has absorbed this patch, so I close this request.

**Pull request closed without merging**
