### PR TITLE
Swin-tiny

### PR DESCRIPTION
**Pull request by huwolong**

### CODE REVIEW

**Comment by Jeffwhen** [comment]
整理下 commit，合成一笔。

**Comment by XiangBin-gh** [comment]
run calibration如果没问题就打开吧

**Comment by huwolong** [comment]
量化还不行，先别打开了。

**Comment by XiangBin-gh** [comment]
附上实测数据

**Comment by huwolong** [comment]
add swin Transformer mlir

    tpu-mlir
    branch: master
    commit id: 127575bfe57b3c1252a8aa015525c0c4d991f3af
    driver
    release 0.4.5

    performace
    name, shape, gops, time(ms), mac_utilization, cpu_usage, ddr_utilization
    swint_bm1684x_f32, 1x3x224x224, 4.500, 41.230, 5.46%, 8.00%, 18.62%

    precision_benchmark
    name, top1, top5
    swint_t-F32, 80.71%, 95.35%

**Pull request merged**
