### PR TITLE
add mm_resnet50 (mlir-1684)

### PR DESCRIPTION
**Pull request by WenjieZhou9**

### CODE REVIEW

**Comment by Jeffwhen** [comment]
1684 和 1684X 相同的配置字段不要重复，可以合理使用 `$(target)` 变量。

**Comment by Jeffwhen** [comment]
删掉 calitable，直接走量化流程。

**Comment by WenjieZhou9** [comment]
tpu-mlir:
branch: master
commit id: 9f76aaaaa2b1ee5262f1e5bd886c3b1d283c27f7
change id: I07704e0aec0c33d7647ba00c3189312fff87457c
libsophon: 0.4.5_amd64


BM684：

name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
mm_resnet50_bm1684_int8_sym,1x3x32x32,2.420,1.495,9.20%,6.00%,46.21%
mm_resnet50_bm1684_f32,1x3x32x32,2.420,4.077,26.98%,5.00%,67.63%

name,top1,top5
mm_resnet50-FP32,79.90%,95.19%
mm_resnet50-INT8,79.51%,95.05%


BM684X：

name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
mm_resnet50_bm1684x_f32,1x3x32x32,2.420,2.672,45.29%,7.00%,53.21%
mm_resnet50_bm1684x_int8_sym,1x3x32x32,2.420,0.623,12.14%,14.00%,59.40%

name,top1,top5
mm_resnet50-FP32,79.90%,95.19%
mm_resnet50-INT8,79.92%,92.91%

**Comment by Jeffwhen** [comment]
1684X 精度没出来。

**Pull request merged**
